language: c

compiler:
  - clang
  - gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf libcurl4-openssl-dev automake libtool lcov

before_install:
  - gem install coveralls-lcov

script:
  - ./autogen.sh && ./configure --enable-urls --enable-coverage && make && make clean clean-coverage coverage-lcov

after_success:
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
